/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#ddd9d8",
        "on-primary-container": "#858383",
        "on-tertiary-container": "#868382",
        "on-primary-fixed": "#1c1b1b",
        "surface-tint": "#5f5e5e",
        "on-surface": "#1c1b1b",
        "error-container": "#ffdad6",
        "secondary-container": "#dde5db",
        "secondary-fixed-dim": "#c1c9c0",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#e6e2df",
        "on-tertiary-fixed": "#1c1b1a",
        "secondary-fixed": "#dde5db",
        "tertiary-container": "#1c1b1a",
        "surface-bright": "#fdf8f8",
        "tertiary": "#000000",
        "on-background": "#1c1b1b",
        "on-surface-variant": "#444748",
        "surface-container-low": "#f7f3f2",
        "on-secondary-fixed": "#161d18",
        "outline-variant": "#c4c7c7",
        "primary-fixed-dim": "#c8c6c5",
        "primary-container": "#1c1b1b",
        "surface-container-highest": "#e5e2e1",
        "surface-container": "#f1edec",
        "error": "#ba1a1a",
        "background": "#fdf8f8",
        "primary": "#000000",
        "on-error": "#ffffff",
        "surface": "#fdf8f8",
        "tertiary-fixed-dim": "#cac6c4",
        "secondary": "#586059",
        "on-tertiary-fixed-variant": "#484645",
        "primary-fixed": "#e5e2e1",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f4f0ef",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#474746",
        "on-secondary-fixed-variant": "#414942",
        "surface-variant": "#e5e2e1",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-high": "#ebe7e6",
        "on-secondary-container": "#5e665f",
        "inverse-surface": "#313030",
        "outline": "#747878",
        "inverse-primary": "#c8c6c5",
        "accent-sage": "#7A827A"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1440px",
        "margin-desktop": "64px",
        "unit": "4px",
        "gutter": "24px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "headline-xl": ["Playfair Display", "serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"]
      },
      fontSize: {
        "headline-xl": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.08em", "fontWeight": "500" }],
        "headline-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "300" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0.01em", "fontWeight": "300" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
